"""
OpenSearch Sink - Send events to OpenSearch/Elasticsearch.

This sink sends transformed audit events to an OpenSearch cluster.
"""
import json
import logging
import requests
from datetime import datetime, timezone
from requests.auth import HTTPBasicAuth

from auditflow_sdk import RejectedEvent, deliver_each

__version__ = "1.1.0"

PROPERTIES = {
    "service-url": "OpenSearch base URL, e.g. http://opensearch:9200 (required)",
    "service-path": "Index path (default: /auditflow/_doc). Batches use <index>/_bulk when the path is "
                    "/<index>/_doc or /<index>/_create",
    "username": "Basic auth username (optional)",
    "password": "Basic auth password (optional)",
    "verify-ssl": "Verify TLS certificates: true/false (default: true)",
}

logger = logging.getLogger(__name__)


def process(event_data: dict, properties: dict) -> dict:
    """
    Process an audit event by sending it to OpenSearch.

    Args:
        event_data: The transformed audit event data
        properties: Configuration properties
            - service-url: OpenSearch base URL (required)
            - service-path: Index path (default: /auditflow/_doc)
            - username: Basic auth username (optional)
            - password: Basic auth password (optional)
            - verify-ssl: Verify SSL certificates (default: true)

    Returns:
        dict: Processing result with OpenSearch response
    """
    # Validate required properties
    service_url = properties.get('service-url')
    if not service_url:
        raise ValueError("Missing required property: 'service-url'")

    # Get configuration
    service_path = properties.get('service-path', '/auditflow/_doc')
    username = properties.get('username')
    password = properties.get('password')
    verify_ssl = properties.get('verify-ssl', 'true').lower() == 'true'

    # Build full URL
    full_url = f"{service_url.rstrip('/')}{service_path}"

    # Prepare headers
    headers = {
        'Content-Type': 'application/json'
    }

    # Add timestamp if not present; copy first to avoid mutating the caller's dict
    if 'timestamp' not in event_data:
        event_data = dict(event_data)
        event_data['timestamp'] = datetime.now(timezone.utc).isoformat()

    # Prepare authentication
    auth = None
    if username and password:
        auth = HTTPBasicAuth(username, password)

    try:
        # Send event to OpenSearch
        logger.info("Sending event to OpenSearch: %s", full_url)
        response = requests.post(
            full_url,
            json=event_data,
            headers=headers,
            auth=auth,
            verify=verify_ssl,
            timeout=10
        )

        response.raise_for_status()

        # Parse response
        result = response.json()

        logger.info("Event sent to OpenSearch successfully. Document ID: %s", result.get('_id', 'unknown'))

        return {
            "sent": True,
            "destination": "opensearch",
            "url": full_url,
            "document_id": result.get('_id'),
            "index": result.get('_index'),
            "result": result.get('result'),
            "status_code": response.status_code
        }

    except requests.exceptions.RequestException as e:
        logger.error("Failed to send event to OpenSearch: %s", e)
        raise RuntimeError(f"Failed to send event to OpenSearch at {full_url}: {e}")
    except Exception as e:
        logger.error("Unexpected error sending event to OpenSearch: %s", e)
        raise RuntimeError(f"Unexpected error: {e}")


def process_batch(events: list, properties: dict) -> list:
    """Index a batch of events with ONE ``_bulk`` request.

    The bulk API answers per document. A document OpenSearch cannot index (HTTP 400: a mapping
    conflict, a malformed field) fails alone and is not retried; a throttled or failed one (429,
    5xx) is retried; the rest are indexed. Document ids are generated by OpenSearch, as for single
    events, so a redelivered event is indexed again: de-duplicate by ``eventId``.

    A ``service-path`` that is not ``/<index>/_doc`` or ``/<index>/_create`` has no bulk form; the
    events are then sent one by one.
    """
    service_url = properties.get('service-url')
    if not service_url:
        raise ValueError("Missing required property: 'service-url'")
    target = _bulk_target(properties.get('service-path', '/auditflow/_doc'))
    if target is None:
        return deliver_each(events, properties, process)
    index, action = target
    bulk_url = f"{service_url.rstrip('/')}/{index}/_bulk"

    username = properties.get('username')
    password = properties.get('password')
    auth = HTTPBasicAuth(username, password) if username and password else None
    verify_ssl = properties.get('verify-ssl', 'true').lower() == 'true'

    now = datetime.now(timezone.utc).isoformat()
    lines = []
    for event in events:
        document = event if 'timestamp' in event else {**event, 'timestamp': now}
        lines.append(json.dumps({action: {}}))
        lines.append(json.dumps(document))
    body = ('\n'.join(lines) + '\n').encode('utf-8')

    try:
        logger.info("Sending %d event(s) to OpenSearch: %s", len(events), bulk_url)
        response = requests.post(bulk_url, data=body, headers={'Content-Type': 'application/x-ndjson'},
                                 auth=auth, verify=verify_ssl, timeout=10)
        response.raise_for_status()
        items = response.json().get('items')
    except Exception as e:  # noqa: BLE001 - the request failed: every event failed
        logger.error("Failed to send a batch to OpenSearch: %s", e)
        return [RuntimeError(f"Failed to send events to OpenSearch at {bulk_url}: {e}")] * len(events)
    if not isinstance(items, list) or len(items) != len(events):
        return [RuntimeError(f"OpenSearch answered {bulk_url} without one item per document")] * len(events)

    outcomes = []
    for item in items:
        result = next(iter(item.values()), {}) if isinstance(item, dict) else {}
        status = result.get('status', 0)
        if 200 <= status < 300:
            outcomes.append({"sent": True, "destination": "opensearch", "url": bulk_url,
                             "document_id": result.get('_id'), "index": result.get('_index'),
                             "result": result.get('result'), "status_code": status})
            continue
        error = result.get('error')
        reason = error.get('reason', error.get('type')) if isinstance(error, dict) else error
        message = f"OpenSearch refused the document with status {status}: {reason}"
        # 400 is about this document's content; everything else (429, 5xx, a blocked or missing
        # index) can pass once the cluster or its configuration is back.
        outcomes.append(RejectedEvent(message) if status == 400 else RuntimeError(message))
    return outcomes


def _bulk_target(service_path: str):
    """(index, bulk action) for ``/<index>/_doc`` or ``/<index>/_create``; None for any other path."""
    if '?' in service_path:
        return None
    parts = [part for part in service_path.split('/') if part]
    if len(parts) == 2:
        if parts[1] == '_doc':
            return parts[0], 'index'
        if parts[1] == '_create':
            return parts[0], 'create'
    return None
